services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.https.address=:443"
      # DNS challenge
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.0.0.1"
      # - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - "--certificatesresolvers.myresolver.acme.email=calebmhusovich@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/certs/acme.json"
      # HTTP Challenge
      # - --certificatesresolvers.myresolver.acme.httpchallenge=true
      # - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      # - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      # - --certificatesresolvers.myresolver.acme.email=calebmhusovich@gmail.com
      # - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
      # - 8080:8080
    networks:
      traefik:
    # environment:
    #   CF_DNS_API_TOKEN: "" # Jok78JgWv3UaNFkfHTOqN7bkFE37oB9CI0rwH8BY
    volumes:
      - /home/calebh/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.rule: Host(`traefik.subdomain.husovich.com`)
      traefik.http.middlewares.traefik-auth.basicauth.users: admin:$$apr1$$Qkdo5P0o$$O4MSg6vcS6wLznMIE43wr.
      traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto: https
      traefik.http.routers.traefik.middlewares: traefik-https-redirect
      traefik.http.routers.traefik-secure.entrypoints: https
      traefik.http.routers.traefik-secure.rule: Host(`traefik.subdomain.husovich.com`)
      traefik.http.routers.traefik-secure.middlewares: traefik-auth
      traefik.http.routers.traefik-secure.tls: true
      traefik.http.routers.traefik-secure.tls.certresolver: myresolver
      traefik.http.routers.traefik-secure.tls.domains[0].main: husovich.com
      traefik.http.routers.traefik-secure.tls.domains[0].sans: "*.subdomain.husovich.com"
      traefik.http.routers.traefik-secure.service: api@internal

  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      traefik:
    labels:
      traefik.enable: true
      # HTTP
      traefik.http.routers.whoami.entrypoints: http
      traefik.http.routers.whoami.rule: Host(`whoami.subdomain.husovich.com`)
      traefik.http.routers.whoami.middlewares: traefik-https-redirect
      traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme: https
      # HTTPS
      traefik.http.routers.whoami-secure.entrypoints: https
      traefik.http.routers.whoami-secure.rule: Host(`whoami.subdomain.husovich.com`)
      traefik.http.routers.whoami-secure.tls.certresolver: myresolver
